### ISSUE TITLE
Create separate databases for each guild

### ISSUE THREAD

**Issue by goatslacker** [enanox/pokedraft-bot#8]
We need separate databases along with a mechanism to be able to load/query these different databases. Having them all in a single central database gets too complicated because of all the layers to keep track of, it's easier to just switch between separate dbs

**Comment by enanox** [comment]
Yeah, it makes sense. Were you thinking about a `guildId` named `.sqlite` file for each (on a cloud instance)?

These days I was trying to wrap my head around the MySQL support, and I was wondering if it wouldn't be best to keep both modes, the current one (`sqlite`) and adding a REST-talking layer (we could easily spun an `express.js` for that matter to start unifying the API).

**Comment by goatslacker** [comment]
yup I was thinking of a `${guildId}.sqlite` folder that we can keep on disk and replicate

**Comment by enanox** [comment]
Landed in [583c72c](https://github.com/enanox/pokedraft-bot/commit/583c72c3a72cc71f113181bb3e9945a41c4189c5)
